a=int(input("Enter first number:"))
b=int(input("Enter second number:"))
print("sum:",a+b)
print("sub:",a-b)
print("mul:",a*b)
print("div:",a/b)
print("flour div:",a//b)
print("module:",a%b)
print("power:",a**b)
